#!/bin/bash

echo "Reference ID    : 43D970B5 (tock.teljet.net)
Stratum         : 3
Ref time (UTC)  : Sat Apr 28 00:24:11 2018
System time     : 0.000306280 seconds slow of NTP time
Last offset     : +0.000051675 seconds
RMS offset      : 0.007293674 seconds
Frequency       : 1.838 ppm slow
Residual freq   : +0.006 ppm
Skew            : 0.922 ppm
Root delay      : 0.028429406 seconds
Root dispersion : 0.022208877 seconds
Update interval : 129.1 seconds
Leap status     : Normal"